// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjNXFHgyqLyGVx1L6C9X4DBOs7bH5Ye2Y',
    appId: '1:655847300768:web:65e2139d55b03fb6d773c5',
    messagingSenderId: '655847300768',
    projectId: 'foodkhana-b31f2',
    authDomain: 'foodkhana-b31f2.firebaseapp.com',
    storageBucket: 'foodkhana-b31f2.appspot.com',
    measurementId: 'G-HM86160JLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKMMOnbaU57W84NeCBBQJs_-S86M6feI4',
    appId: '1:655847300768:android:f66b1335da6bf0ded773c5',
    messagingSenderId: '655847300768',
    projectId: 'foodkhana-b31f2',
    storageBucket: 'foodkhana-b31f2.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkN3aUYKHbwOvBTorAmdCR7OGjMVRsILg',
    appId: '1:655847300768:ios:a4e9b644e004b24cd773c5',
    messagingSenderId: '655847300768',
    projectId: 'foodkhana-b31f2',
    storageBucket: 'foodkhana-b31f2.appspot.com',
    iosClientId:
        '655847300768-q6qe5khgmip4gsgjj9qtom0vnodhlecc.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodkhana',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkN3aUYKHbwOvBTorAmdCR7OGjMVRsILg',
    appId: '1:655847300768:ios:3f6681e5a1e41db6d773c5',
    messagingSenderId: '655847300768',
    projectId: 'foodkhana-b31f2',
    storageBucket: 'foodkhana-b31f2.appspot.com',
    iosClientId:
        '655847300768-ltr5dm0mot1ij1ngsb5tqleff16s99dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodkhana.RunnerTests',
  );
}
